### ISSUE TITLE
model.cfg error

### ISSUE THREAD

**Issue by thegodone** [WeilabMSU/PretrainModels#1]
I am trying the new method and have found and fix several minor issues but I still have missing file like "encoder.json" : 
```
llm path dict: ['./examples/models/chembl27_512/']
| dictionary: 72 types
Traceback (most recent call last):
  File "/Users/tgg/Github/PretrainModels/./bt_pro/generate_bt_fps_new.py", line 143, in <module>
    cli_main()
  File "/Users/tgg/Github/PretrainModels/./bt_pro/generate_bt_fps_new.py", line 139, in cli_main
    main(args)
  File "/Users/tgg/Github/PretrainModels/./bt_pro/generate_bt_fps_new.py", line 109, in main
    extract_smiles_embedding(
  File "/Users/tgg/Github/PretrainModels/./bt_pro/generate_bt_fps_new.py", line 77, in extract_smiles_embedding
    model = RobertaModel.from_pretrained(model_name_or_path, checkpoint_file)
  File "/Users/tgg/Github/PretrainModels/bt_pro/fairseq/models/roberta/model.py", line 155, in from_pretrained
    return RobertaHubInterface(x['args'], x['task'], x['models'][0])
  File "/Users/tgg/Github/PretrainModels/bt_pro/fairseq/models/roberta/hub_interface.py", line 27, in __init__
    self.bpe = encoders.build_bpe(args)
  File "/Users/tgg/Github/PretrainModels/bt_pro/fairseq/registry.py", line 34, in build_x
    return builder(args, *extra_args, **extra_kwargs)
  File "/Users/tgg/Github/PretrainModels/bt_pro/fairseq/data/encoders/gpt2_bpe.py", line 33, in __init__
    encoder_json = file_utils.cached_path(
  File "/Users/tgg/Github/PretrainModels/bt_pro/fairseq/file_utils.py", line 155, in cached_path
    raise EnvironmentError("file {} not found".format(url_or_filename))
OSError: file /gpfs/wscgpfs02/chendo11/workspace/matai/Dataset/encoder.json not found
```

**Comment by thegodone** [comment]
I find the solution by downloading the encoder and vocabulary locally and rename the paths accordingly. I have a new error
```
    model.bpe = CustomSMI2BPE(model.cfg)
  File "/Users/tgg/.local/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1614, in __getattr__
    raise AttributeError("'{}' object has no attribute '{}'".format(
AttributeError: 'RobertaHubInterface' object has no attribute 'cfg'
```

**Comment by thegodone** [comment]
I fix it by using instead of cfg the model.args values and use every in generate_bt_fps_new.py  model.args.xxx for the needed parameters.

**Comment by thegodone** [comment]
I have to edit and review only the following files:
./bt_pro/fairseq/models/roberta/hub_interface.py
./bt_pro/fairseq/checkpoint_utils.py
./bt_pro/fairseq/data/encoders/gpt2_bpe.py
./bt_pro/generate_bt_fps_new.py
./bt_pro/fairseq/tasks/masked_lm.py
and download the "encoder and vocab json files"
